# Generated by Django 3.0.4 on 2020-03-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedsmartphone',
            name='site',
            field=models.CharField(default='sadfasd', max_length=200),
            preserve_default=False,
        ),
    ]
