# Generated by Django 3.0.4 on 2020-03-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_originallaptop_scrapedlaptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedlaptop',
            name='searched',
            field=models.BooleanField(default=False),
        ),
    ]
