# Generated by Django 3.0.4 on 2020-03-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scrapedlaptop_searched'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=50)),
                ('client_ip', models.CharField(max_length=40)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
