# Generated by Django 3.0.4 on 2020-03-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='user_agent',
            field=models.CharField(default='none', max_length=400),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AccessLog')),
            ],
        ),
    ]
