# Generated by Django 3.0.4 on 2020-03-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200330_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalsmartphone',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapedsmartphone',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
