# Generated by Django 3.0.4 on 2020-03-31 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200330_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedsmartphone',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.OriginalSmartphone'),
        ),
    ]
